name: chambea
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  location: ^7.0.1
  permission_handler: ^11.3.1
  path_provider: ^2.0.12
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.0
  image_picker: ^0.8.7+3
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # <-- added for app icon generation

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/search.png
    - assets/images/active_service.png
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
