// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrsDB7eYDpluV8jaBPLsTF9ZsNuvYM28E',
    appId: '1:132354394234:web:703beb60a854100a0d13c3',
    messagingSenderId: '132354394234',
    projectId: 'client-chambea',
    authDomain: 'client-chambea.firebaseapp.com',
    storageBucket: 'client-chambea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcsOnv8P90FM9lgc3HaXQnvr_CKVGoqV4',
    appId: '1:132354394234:android:1195e21b6ab5fd770d13c3',
    messagingSenderId: '132354394234',
    projectId: 'client-chambea',
    storageBucket: 'client-chambea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmOcPQXvFL9hnsPZySq9FW_cvxqvcHB2k',
    appId: '1:132354394234:ios:e61f4b803470a83f0d13c3',
    messagingSenderId: '132354394234',
    projectId: 'client-chambea',
    storageBucket: 'client-chambea.firebasestorage.app',
    androidClientId: '132354394234-l26oqphl5obnjs7mudbmighngc0grn31.apps.googleusercontent.com',
    iosClientId: '132354394234-lips37nopasjsstgi0aeravocc7163b5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chambea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmOcPQXvFL9hnsPZySq9FW_cvxqvcHB2k',
    appId: '1:132354394234:ios:e61f4b803470a83f0d13c3',
    messagingSenderId: '132354394234',
    projectId: 'client-chambea',
    storageBucket: 'client-chambea.firebasestorage.app',
    androidClientId: '132354394234-l26oqphl5obnjs7mudbmighngc0grn31.apps.googleusercontent.com',
    iosClientId: '132354394234-lips37nopasjsstgi0aeravocc7163b5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chambea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrsDB7eYDpluV8jaBPLsTF9ZsNuvYM28E',
    appId: '1:132354394234:web:ca6498f5f0d0907b0d13c3',
    messagingSenderId: '132354394234',
    projectId: 'client-chambea',
    authDomain: 'client-chambea.firebaseapp.com',
    storageBucket: 'client-chambea.firebasestorage.app',
  );

}