// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBELZepUzHuskwtTCgxy3yGaBFTQ-4q6XI',
    appId: '1:317466770837:web:271877bf7f5f31bb72ca9c',
    messagingSenderId: '317466770837',
    projectId: 'chambeaapp-6a037',
    authDomain: 'chambeaapp-6a037.firebaseapp.com',
    storageBucket: 'chambeaapp-6a037.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7a58jkgdVnxBvKug2km62hySPnls0hu0',
    appId: '1:317466770837:android:25438e628ceca05672ca9c',
    messagingSenderId: '317466770837',
    projectId: 'chambeaapp-6a037',
    storageBucket: 'chambeaapp-6a037.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo5xGgeL7jejR0N_Z7RJKznFkqHSMvcrM',
    appId: '1:317466770837:ios:038f882d8b68929172ca9c',
    messagingSenderId: '317466770837',
    projectId: 'chambeaapp-6a037',
    storageBucket: 'chambeaapp-6a037.firebasestorage.app',
    iosBundleId: 'com.example.chambea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo5xGgeL7jejR0N_Z7RJKznFkqHSMvcrM',
    appId: '1:317466770837:ios:038f882d8b68929172ca9c',
    messagingSenderId: '317466770837',
    projectId: 'chambeaapp-6a037',
    storageBucket: 'chambeaapp-6a037.firebasestorage.app',
    iosBundleId: 'com.example.chambea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBELZepUzHuskwtTCgxy3yGaBFTQ-4q6XI',
    appId: '1:317466770837:web:2e34153b7d298e1972ca9c',
    messagingSenderId: '317466770837',
    projectId: 'chambeaapp-6a037',
    authDomain: 'chambeaapp-6a037.firebaseapp.com',
    storageBucket: 'chambeaapp-6a037.firebasestorage.app',
  );
}
