// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJPQdZJH298C2AcESwb8UB5QrORrZHREM',
    appId: '1:268154597894:web:2a32cc0054b590562f4987',
    messagingSenderId: '268154597894',
    projectId: 'clientchambeaapp-aa95d',
    authDomain: 'clientchambeaapp-aa95d.firebaseapp.com',
    storageBucket: 'clientchambeaapp-aa95d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQaXUqh5bPQBwjGLJHoerpXv1ytOyEaro',
    appId: '1:268154597894:android:fe256a0ba709ca9a2f4987',
    messagingSenderId: '268154597894',
    projectId: 'clientchambeaapp-aa95d',
    storageBucket: 'clientchambeaapp-aa95d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Qrv33KzwJhPnbArtha6rGffzH7Im6kk',
    appId: '1:268154597894:ios:21eaa388962b076e2f4987',
    messagingSenderId: '268154597894',
    projectId: 'clientchambeaapp-aa95d',
    storageBucket: 'clientchambeaapp-aa95d.firebasestorage.app',
    iosBundleId: 'com.example.chambea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Qrv33KzwJhPnbArtha6rGffzH7Im6kk',
    appId: '1:268154597894:ios:21eaa388962b076e2f4987',
    messagingSenderId: '268154597894',
    projectId: 'clientchambeaapp-aa95d',
    storageBucket: 'clientchambeaapp-aa95d.firebasestorage.app',
    iosBundleId: 'com.example.chambea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJPQdZJH298C2AcESwb8UB5QrORrZHREM',
    appId: '1:268154597894:web:fc7c8e7fb4ac86cd2f4987',
    messagingSenderId: '268154597894',
    projectId: 'clientchambeaapp-aa95d',
    authDomain: 'clientchambeaapp-aa95d.firebaseapp.com',
    storageBucket: 'clientchambeaapp-aa95d.firebasestorage.app',
  );
}
